export default {
	'access_token': 'EAACErDEWMSoBAPOTuRFZBTZA3BMbaw40lHhEyF6pi4ZAU4VtOd9gggSGFZAKAoMcumdUABlSZCfxdYH8WlJ5t3NvXgokAjIf6fTqhezMcBfGPtb6vKeTp28I669AKfhohiIOsLMntZCQWRo3iNzLRvryVsmkqpa7mwZBy03TpAwMAZDZD'
};